### ISSUE TITLE
VM won't load into VB

### ISSUE THREAD

**Issue by Mark92630** [ChiralBehaviors/Ultrastructure#31]
Running VirtualBox 4.3.24 and attempted a "Machine .. Add..." of the .vbox file. Doesn't work.

![screen shot 2015-03-11 at 23 19 25](https://cloud.githubusercontent.com/assets/8611158/6613107/2b26245a-c845-11e4-8cd6-7a34418f21d0.png)

**Comment by Hellblazer** [comment]
We are in the process of just cutting a branch which no longer requires a VM. Pleas stay tuned.

**Comment by Mark92630** [comment]
Will do. Hope none of those 18 years of pounding your head against a brick wall were caused by the technical errors in the 1995 CACM article.

**Comment by Hellblazer** [comment]
Heh. No. 

It's always been the struggle of understanding. 

We'll be making the branch master soon. It's winnow-jsp. No more java stored procedures. :)

You can pull that branch if you like. Only requires a 9.x Postgres installation.

**Comment by Hellblazer** [comment]
Branch has been merged into master.  No longer needing a VM install with pl/java.
