### ISSUE TITLE
What are the system requirements for installation?

### ISSUE THREAD

**Issue by Mark92630** [ChiralBehaviors/Ultrastructure#33]
What Operating Systems are supported? For each supported Operating System, what optional software, if any, needs to be installed first?

To give you one concrete example, I am running Mac OS X 10.10.2 (Yosemite), with PostgreSQL 9.4 installed and operational (pgAdmin3 is able to connect), and when I open Terminal and "cd" to the "Ultrastructure-master" directory and issue the "mvn clean install" command, I get an error response "-bash: mvn: command not found".

I've been running VM VirtualBox for at least a couple of years (and Parallels for several years before that), and have successfully deployed both Windows 7 and Ubuntu 14 guests. So, I will have no problem (at least I don't think) conforming to your requirements for a successful installation. I just have to know what they ARE.

In summary, right now I am trying and failing to get this running on OS X (the host O/S on my iMac). I'd be happy to try it on an Ubuntu guest VM, if that is what is really required. I just don't know. What I would prefer, by the way, is to clone your development environment as closely as possible in my own VM. I think that will reduce the chances of unexpected problems as I try to get this running for the first time.

But what I need, sadly, are step-by-step instructions that could be followed by a ten-year-old with no prior sysadmin or developer experience, on a CLEAN BOX with nothing beyond the absolute bare minimum O/S installation (your choice of O/S). Feel free to assume that I can read and type English.  :-)

P.S. What, exactly, is BEING installed, beyond the creation of PostgreSQL tables and stored procedures?

TIA,

Mark

**Comment by Hellblazer** [comment]
In the new readme.md, there is a link to the postgre installation page.  As well as cleaned up instructions.  I develop on mac/Yosemite and os/x installation works great. If you use this, the defaults all work if you choose "postgres" as the password for the postgres user/db. It's an option in the install. 

Do let me know if this isn't sufficient to get the build running. 

Developing for our US implementation will take a bit of wiki documentation that we have yet to write. But feel free to add issues. We'll respond as best we can.

**Comment by Hellblazer** [comment]
As to what is installed beyond DDL, nothing anymore. We used to use pl/java for the stored procedure implementation. That is not true anymore. We eliminated that with the current HEAD on master.

**Comment by Mark92630** [comment]
README.md tells me to issue the command: "mvn clean install". This fails with the error message:

"-bash: mvn: command not found"

PostgreSQL 9.4.1 is already installed and running when I try to execute the mvn command.

**Comment by Hellblazer** [comment]
Ah.  Apologies.  Apache Maven is what we use for the build system.  I'll update the readme.   

In the mean time, you'll need to install Apache maven: http://maven.apache.org/
You will also need the Java 1.8 JDK installed.  See here: http://is.gd/Ez20hQ for download.
Apache maven is a build system, and "mvn" is the command to run it.

Again, let me know if you run into trouble.  If you're not familiar with Java and Maven builds, it should be all right.  But you'll probably need some pointers, as it's not necessarily obvious how things are laid out or organized if you're new to Maven and Java.

**Comment by Mark92630** [comment]
It took me about three hours to get my JDK upgraded to the latest 1.8, get Maven 3.2.5 installed, and (this was a significant chunk of it) get Maven to recognize that JDK. There are things that aren't mentioned in the installation instructions from Oracle and Apache. I realize that those aren't under your control.

Anyway, I ran your "mvn clean install" command, and the -P database.active clean install. The latter ran through two series of tests with no errors. But now I can't see any of the Ultra-Structure tables in PostgreSQL, at least not through pgAdmin3. Are they still there in the database? The only schema I can see is "public" and I would guess that's not the one you're using.

**Comment by Hellblazer** [comment]
It's in a new database called "core". You should see that db when you connect to postgres via pgadmin

**Comment by Mark92630** [comment]
O.K., got it. I had to change the password from what I had originally used when I installed the database software, and reconnect. You have a LOT more tables than in the original CACM article (but that is the subject of another issue). We can close this one.
